#!/bin/bash -l

## STANDARD OUTPUT AND ERROR: ---------------

#SBATCH -o ./jobNECI.out.%j 
#SBATCH -e ./jobNECI.err.%j

## INITIAL WORKING DIRECTORY ---------------

#SBATCH -D ./

## JOB NAME ---------------------------------

#SBATCH -J fe(10e7o)

## NUMBER OF NODES AND MPI TASKS PER NODE --

#SBATCH --exclusive
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cores-per-socket=1
#SBATCH --sockets-per-node=1
#SBATCH --mem=0

## WALL CLOCK LIMIT ------------------------

#SBATCH --time=02:00:00
#SBATCH --partition=p.2h.big

## NETWORK TYPE ----------------------------

##SBATCH --network DEVTYPE=IB

## MODULE LOADING --------------------------

module purge

module load gnu-openmpi/3.1.6

## SET-UP PREAMBLE -------------------------

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

ulimit -s unlimited

## NECI RUN --------------------------------

srun --mpi=pmix /home/dimauro/neci/build_gnu3.1.6_fkf_cluster_amdlogin1/bin/neci < NECI.in >> NECI.out 2>>NECI.err

## POST-PROCESSING -------------------------
