#!/bin/bash
#SBATCH -J vd[n=5]
#SBATCH -o output
#SBATCH --mem=0
#SBATCH --nodes=64
#SBATCH --ntasks=8192
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-core=1
#SBATCH --time=24:00:00
#SBATCH --partition=apu

ulimit -s unlimited 2> /dev/null
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export GOTO_NUM_THREADS=1
export BLAS_NUM_THREADS=1
export ATLAS_NUM_THREADS=1
. /etc/profile.d/modules.sh ;       module purge ; module load intel/2024.0 impi/2021.11

echo "Run started: $(date)"
echo "Using VDAGGER_ARCH = intel24_viper_cluster"
echo "Running 1x128 MPI processes."
echo
srun /u/mdimauro/vdagger/build_intel24_viper_cluster_main_opt/bin/vdagger "input.casl"
echo
echo "Run ended: $(date)"
rm -f ".vdagger.lock"
